### ISSUE TITLE
コメントの終了と開始が同じ行にある場合正確にカウントされない

### ISSUE THREAD

**Issue by yonezawahr** [takezoe/stepcounter#16]
例えば下記の例(l.6)のように、コメントの終了と開始を
同じ行に記述してしまった場合、コメントの開始が正しく
識別されず、実行行と判定されてしまう。

``` html
l.1 <html>
l.2   <body>
l.3
l.4   <!-- comment 
l.5     <b></b>
l.6   --><!-- comment 
l.7     <b></b>
l.8     <b></b>
l.9   -->
l.10
l.11  </body>
l.12 </html>
```

上記の例では、カウント結果は以下のようになり、実行行が7行とカウントされる。
(l.6～l.8が実行行と判定)

ファイル 種類 カテゴリ 実行 空行 ｺﾒﾝﾄ 合計 
*****.html HTML 7 2 3 12

**Comment by takezoe** [comment]
#33 の修正で解消されているのではないかと思います。
