### ISSUE TITLE
[[IGNORE]]があるとNullPointerExceptionが発生する

### ISSUE THREAD

**Issue by ghost** [takezoe/stepcounter#25]
[[IGNORE]]があるとNullPointerExceptionが発生します。
(GUIの場合は、結果が何も出力されない)

ご確認のほど、よろしくお願いいたします。

**Comment by niwashun** [comment]
@takezoe StepCounter 実装クラスを見ると IGNORE_PATTERN にマッチした際は null を返すので、以下の箇所で null の場合に空の CountResult 配列を返すようにすればいいと思います。

https://github.com/takezoe/stepcounter/blob/6df3369339f5ab7d5b3a4cd430f2e4fa84d9003d/core/stepcounter/src/main/java/jp/sf/amateras/stepcounter/Main.java#L85-L86

**Comment by takezoe** [comment]
こんな感じで修正しました。 ed9d06135e8e10096e843f693ba9490454cd80c0
